id: I03BB7F49
legacy_id: P000808
ocr_import_info:
  bdrc_scan_id: W30416
  source: bdrc
  ocr_info:
    timestamp: '2021-04-05T05:07:41'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T11:19:51.661632+00:00'
last_modified: 2022-08-27 19:20:19.197620
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W30416
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW30416
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མི་ཉག་འཇམ་དབྱངས་གྲགས་པའི་རང་རྣམ།
  author: རི་ཁྲོད་ཀྱི་དབང་ཕྱུག་འཇམ་དབྱངས་གྲགས་པ།
statistics:
  ocr_word_mean_confidence_index: 0.9781314629835491
  ocr_word_median_confidence_index: 0.99
quality: null
bases:
  I1PD28133:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD28133
      total_pages: 362
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD28133.txt
    statistics:
      ocr_word_median_confidence_index: 0.99
      ocr_word_mean_confidence_index: 0.9781314629835491
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
