id: opecha:P000808
initial_creation_type: ocr
source_metadata:
  id: bdr:W30416
  title: མི་ཉག་འཇམ་དབྱངས་གྲགས་པའི་རང་རྣམ།
  volumes:
    e72bb11c4ef64abfbfc51800d5458838:
      image_group_id: I1PD28133
      title: ''
      base_file: v001.txt
  author: ''
