id: P000808
initial_creation_type: ocr
created_at: 5/04/2021
last_modified_at: 2021-12-17 10:11:41.323668
source_metadata:
  id: bdr:W30416
  title: མི་ཉག་འཇམ་དབྱངས་གྲགས་པའི་རང་རྣམ།
  volumes:
    e72bb11c4ef64abfbfc51800d5458838:
      image_group_id: I1PD28133
      title: ''
      base_file: v001.txt
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
